name: Deploy Server

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - 'package*.json'
      - '.github/workflows/deploy-server.yml'

env:
  PROJECT_ID: grantrigbydev
  REGION: us-central1
  SERVICE_NAME: freelance-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |
          docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} -f server/Dockerfile .
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          env_vars: |
            NODE_ENV=production
            PORT=8080
            DOMAIN=freelance.grantrigby.dev
          secrets: |
            DATABASE_URL=freelance-db-url:latest
            GOOGLE_CLIENT_ID=google-client-id:latest
            GOOGLE_CLIENT_SECRET=google-client-secret:latest
